### ISSUE TITLE
Connecting to Wi-Fi during onboarding doesn't work

### ISSUE THREAD

**Issue by jlnr** [elementary/triage#326] opened 2023-09-09 14:47 UTC
### What Happened?

In the onboarding UI of a fresh elementary OS installation, there is a screen that reminds the user to connect to Wi-Fi.

However, at this point I have never successfully connected to Wi-Fi. I am not sure why, but after entering the password, I don't see any progress or error. The drop-down list looks like I never touched it.

https://github.com/elementary/triage/assets/70772/b2b0fd1f-1b0d-49ee-8371-b8320e8730c1

Once I am past the onboarding UI, it always works immediately. This behavior was the same in each of my recent elementary OS installations (all based on recent Daily ISOs).

### Steps to Reproduce

1. Install elementary OS
2. Reboot
3. Try to connect to Wi-Fi during onboarding

### Expected Behavior

Wi-Fi should work during onboarding. (Actually, it would be even nicer if the installer could remember which Wi-FI I connected to for installing Nvidia drivers, but that sounds like a completely new feature.)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Not sure where to look for logs?
```

### Hardware Info

This is with an Intel Wi-Fi chip that shouldn't require any additional drivers. It also works during the live session.

**Comment by danirabbit** [comment] 2023-09-09 16:22
Duplicate of https://github.com/elementary/greeter/issues/615

**Closed as not planned** 2023-09-09 16:22 UTC

**Comment by jlnr** [comment] 2023-09-10 19:04
Oh sorry, I only looked at the onboarding project, not greeter. 👍

Edit: Ah, and there's also initial-setup. That was the one I was looking for.
