### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by MIMO-PIESEK** [elementary/triage#670] opened 2024-12-30 10:30 UTC
### Discussed in https://github.com/orgs/elementary/discussions/669

<div type='discussions-op-text'>

<sup>Originally posted December 30, 2024</sup>
hey, I have a problem with the font in elementary os 8, everything was great but the font is unreadable and I don't know what it says. please help - I donated to elementaryOs
screen shots:
![Zrzut ekranu z 2024-12-30 11 19 36](https://github.com/user-attachments/assets/0d9d8d59-7f1d-4adf-98d8-53f620508d00)
</div>

**Comment by ryonakano** [comment] 2024-12-30 10:32
Duplicate of elementary/triage#651

**Closed as not planned by ryonakano** 2024-12-30 10:32 UTC
Labels: Status: Duplicate
