### ISSUE TITLE
Lock Screen: Clock does not update after resume

### ISSUE THREAD

**Issue by marbetschar** [elementary/triage#36] opened 2020-09-21 06:03 UTC
## Describe the bug

When I suspend my laptop and open the lit after a few hours, the lock screen's clock shows an old time. It seems it does not get updated after the laptop is awake again.

![Screenshot from 2020-09-21 08-02-42](https://user-images.githubusercontent.com/392542/93736515-e74c3a00-fbe0-11ea-8e61-54185f5e5913.png)

**Comment by vjr** [comment] 2020-09-21 07:38
This is a duplicate of https://github.com/elementary/greeter/issues/306

I have created a fix in this pending PR https://github.com/elementary/greeter/pull/472

It may take a while so we need to be patient to see if this proposed fix is acceptable.

**Closed as completed** 2020-10-29 22:25 UTC
Labels: Status: Duplicate
