### ISSUE TITLE
Font scaling issue with JAVA based apps

### ISSUE THREAD

**Issue by fayjies** [elementary/triage#94] opened 2021-11-07 22:47 UTC
### What Happened?

The Inter font (even the font for dyslexia) in eOS 6 is in .otf format. The JAVA-based apps usually fail to scale .otf format fonts. So, JAVA-based apps looks weird in eOS 6 by default. (It does not occur in eOS 5, as the default Roboto font is in .ttf format)
![pdf_studio_viewer](https://user-images.githubusercontent.com/32283602/140664393-a8adca54-68b6-4586-a491-d69bf2731923.png)

![sweet-home-3d](https://user-images.githubusercontent.com/32283602/140664395-1f272047-a903-491f-ab43-b0edb8aa4683.png)

Here I attach four screenshot of two JAVA-based apps (PDF Studio Viewer, and Sweet Home 3D). The first screenshot for each app represents the default inter font (.otf) of eOS 6. The second screenshot for each app represents the same font (Inter) in TTF format (Downloaded from Google font).

### Steps to Reproduce

For PDF Studio Viewer:
1. Download PDF studio viewer from [here](https://www.qoppa.com/pdfstudioviewer/ )
2. Install it, and open it. It will show the font scaling issue with the opened window.

For Sweet Home 3D:
1. Download the flatpak for Sweet Home 3D from [flathub](https://flathub.org/apps/details/com.sweethome3d.Sweethome3d)
2. Install it, and open it. It will show the font scaling issue with the opened window.

Solution Proposed:

Convert both the default fonts: Inter and Dyslexia font to TTF format and provide it as TTF by default in eOS 6. (even in eOS 7)

### Expected Behavior

We expect the font scaling as follows:

![pdf-studio-viewer-ttf](https://user-images.githubusercontent.com/32283602/140664394-f1796f5a-481b-4cea-a213-116f9110a945.png)

![sweet_home-3D-ttf](https://user-images.githubusercontent.com/32283602/140664396-0fd66b3c-a6fe-4b30-aee4-313cd5e79e2c.png)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2024-01-07 17:33
Duplicate of https://github.com/elementary/triage/issues/55

**Closed as not planned by lenemter** 2024-01-07 17:33 UTC
Labels: Status: Duplicate
