### ISSUE TITLE
The title bar of some apps still keep white when turn global & app's color theme to dark

### ISSUE THREAD

**Issue by sauntor** [elementary/triage#267] opened 2023-07-09 08:12 UTC
### What Happened?

Apps like VSCode, Chrome, VLC, etc., would keep it's title bar in white, even if you turn color theme to dark in swithboard or the app's settings/preferences

### Steps to Reproduce

Take VSCode for example:
1. install visual studio code
2. change` vscode`'s color theme to `Solarized Dark`
3. Open system's `Settings` -> `Desktop` -> `Appearance`, and set `Style` to `Dark`
4. Close VSCode, and reopen it again
5. you'll find it's title bar is still white

### Expected Behavior

All title bars should be dark too.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-07-09 11:32
Hi, thanks for reporting! This is actually a duplicate of https://github.com/elementary/gala/issues/956. Gala doesn't actually handle SSD titlebars, mutter does this. So I think this will be fixed in OS 8.

**Closed as not planned by lenemter** 2023-07-09 11:32 UTC
Labels: Status: Duplicate
