### ISSUE TITLE
Option to enable restricted drivers on install. 

### ISSUE THREAD

**Issue by douglangille** [elementary/triage#79] opened 2021-08-16 11:32 UTC
## Problem

On a laptop that doesn’t have a built-in Ethernet port, installing Broadcom wifi drivers is difficult. Sample system: 2015 MacBook Air. 

## Proposal

Include the option to install restricted drivers, hwe kernel modules, and their dependencies upon liveboot and install. Specifically, Ubuntu Restricted Drivers. 

## Prior Art

Hera had this option.

**Comment by davidmhewitt** [comment] 2021-08-16 12:30
Thanks for the report!

There's already an issue and some related discussion about this here: https://github.com/elementary/installer/issues/418

I'll close this as a duplicate of that.

**Closed as completed by davidmhewitt** 2021-08-16 12:30 UTC
