### ISSUE TITLE
Odin: add-apt-repository throws aptsources.distro.NoDistroTemplateException

### ISSUE THREAD

**Issue by marbetschar** [elementary/triage#37] opened 2020-10-01 05:19 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If I execute `sudo add-apt-repository ...` on Odin, it throws the following exception:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/next
```

I'm aware that add-apt-repo isn't recommended. But it would be nice if it works - for sure not a high priority though ;)

**Comment by ryonakano** [comment] 2020-10-01 05:23
Duplicate of https://github.com/elementary/os/issues/399, I'm not sure which triage or os repo is suitable for this issue though.

**Closed as completed** 2020-10-29 22:29 UTC
Labels: Status: Duplicate
