### ISSUE TITLE
Hera 5.1 hangs and errors on second login

### ISSUE THREAD

**Issue by Djcoper** [elementary/triage#2] opened 2019-12-04 07:31 UTC
To reproduced simply log into a session, the first logon is fine no issues you must log out then log in a second time then system will hang up black screen for a very long time then when the desktop finally shows up wingpanel is not working and the logout button and shutdown,restart buttons are also not working pressing the power button causes  immediate system shut down.

This happen to me with a fresh install of 5.1 on two different computers Dell Inspiron 5378 and an dell latitude 3550.

**Comment by panicsteve** [comment] 2020-01-01 19:07
I just came here to file this same issue. 

I wasn't sure how to describe it, so I made a video, which you can view here (approximately 180MB): https://stevenf.com/downloads/elementary-login.mp4

In the video you can see:

1. First login happens quickly (about 3 seconds)
2. Can successfully log back out
3. Second login takes nearly 30 (!) seconds
4. Wingpanel says I'm logged out while I'm logged in
5. Log out command no longer works

I am happy to provide logs or diagnostic info, but I'll need guidance on what you'd like me to submit and where I can find it.

My system info:

![71629609-4e3d4500-2bb3-11ea-9a35-1cd55d873086](https://user-images.githubusercontent.com/196190/71645037-b9a41700-2c86-11ea-9285-68b0d0a858cc.png)

**Comment by cassidyjames** [comment] 2020-01-04 03:53
I can also reproduce this. It seems like there's some bus or something the session is waiting for, possibly related to the greeter?

**Comment by cassidyjames** [comment] 2020-02-18 18:39
Thanks for reporting this. It seems the root cause is here: https://github.com/elementary/cerbere/issues/36

As such, I'll be closing this as a duplicate but you can follow along at this project: https://github.com/orgs/elementary/projects/67

**Closed by cassidyjames** 2020-02-18 18:39 UTC
Labels: Priority: Medium, Status: Confirmed
