### ISSUE TITLE
right click problem

### ISSUE THREAD

**Issue by Arnab11** [elementary/triage#3] opened 2019-12-06 09:49 UTC
when I am selecting a text and right click on it in any browser it automatically opens inspect elements.  I think it is the issue with mouse but i tried with 3 different mouse, the issue is remain same.

**Comment by danirabbit** [comment] 2024-10-23 17:45
This is really old and I can't reproduce this, so closing as "incomplete". OP feel free to reopen following the issues template if you can reproduce this issue

**Closed as not planned by danirabbit** 2024-10-23 17:45 UTC
Labels: Status: Out of Scope
