### ISSUE TITLE
Ship eOS with libinput-gestures to enable multitouch gesture OOTB

### ISSUE THREAD

**Issue by Fatih20** [elementary/triage#26] opened 2020-04-01 15:54 UTC
## Feature
**Is your feature request related to a problem? Please describe.**
Multitouch gesture is not enabled in elementaryOS out-of-the-box. Even though it's really useful for certain people. Mac users for example, are probably used to do swipe 3 fingers up to see their all of the windows they have opened. 

**Describe the solution you'd like**
To enable multitouch gestures, we would need to [libinput-gestures](https://github.com/bulletmark/libinput-gestures) installed. So, if we want multitouch gestures out-of-the-box we'd need to have this shipped out-of-the-box.

IMHO, it'd really compliment elementary OS thorough design of its UI/UX. We have a carefully planned set of keyboard shortcut, it'd be nice to have a carefully planned gestures also.

**Comment by alice-mkh** [comment] 2020-04-01 16:54
libinput-gestures is a pretty hacky implementation, and the UX suffers as you can't do 1-to-1/stick to finger gestures. To do it properly, elementary would need to switch to Wayland from X11 first, then it can easily have the same kind of gestures GNOME has. :)

**Comment by Fatih20** [comment] 2020-04-01 16:56
Is there any plan for eOS to move to Wayland?

**Comment by alice-mkh** [comment] 2020-04-01 16:57
Yes, but it's a long process.

**Comment by danirabbit** [comment] 2020-05-05 17:44
Closing as a duplicate of https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/16

**Closed as completed by danirabbit** 2020-05-05 17:44 UTC
